### ISSUE TITLE
I JUST WANT TO SAY THANKS!!

### ISSUE THREAD

**Issue by mogocat** [hilogames/HLSpriteKit#1]
It's so amazing for what you did. It's really useful for me and maybe the most useful tool I have ever used. Thanks for your great job! YOU SAVED MY LIFE!

**Comment by karlvoskuil** [comment]
I'm really glad to hear that! I see a lot of room for improvement and expansion, so let me know if you run into any trouble or have ideas for features.

**Comment by mogocat** [comment]
I had written games with spritekit and swift for about six months. And three of the games had been published on app store. We got three guys making game together, and we just found that there's a lot of work to do if we want a bigger game. So I want to combine some spritekit libs on github which are useful for making 2D games. Maybe we got a new game engine. What's your opinion? I really need some advices before I do this.

**Comment by karlvoskuil** [comment]
I'm afraid I don't have enough experience yet to see the big picture. My lib solves some specific problems I had, but I don't know if it solves them in the best way. (For instance, HLSpriteKit allows using `UIGestureRecognizers` with SpriteKit. But is that a good idea?) So . . . I'm not sure.
But, feel free to use my code!

**Comment by mogocat** [comment]
Thanks very much for that! I am afraid that I don't have more experience than you, but I prefer better game than better code. So it's enough for me to make them just work right together.  : ) 

Maybe I will got a great tool set or just many bugs. But I want to try. May god bless me! : )
(BTW: sorry for my poor English)

**Comment by mogocat** [comment]
What can I do to release my scene from memory when they are uselessly? My memory keeps increasing when I present new scenes in one skView. It seems that the old scene is still in the memory. Had you got  those problems?

**Comment by mogocat** [comment]
I am not sure that whether there is a retain reference of the scene, so I just create a new project and add scenes to the skView, and I got the same result. Any help will be appreciated!

**Comment by karlvoskuil** [comment]
I don't see an obvious retain cycle in HLScene. The UIGestureRecognizers retain their delegate, but I'm guessing you didn't add any gesture recognizers to your test.

In your test, do you get the same behavior when adding lots of `GameScene` scenes (created by the project template), or does it only happen when you add lots of `HLScene` scenes?
