### ISSUE TITLE
Is there an easier way to set the color of a square in HLGridNode?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#11]
I basically just want to have a little enhancement on HLGridNode. Right now, I'm using this code to change the color of an individual square:

```
(grid!.squareNode(forSquare: 0) as! HLBackdropItemNode).normalColor = UIColor.blue
```

Maybe you can just make `squareNode(forSquare:)` return an `HLBackdropItemNode` instead? Alternatively, can you make a method like this:

```
grid!.setColor(forSquare: 0, to: UIColor.blue)
```

Or can you both do of these enhancements? I am not familiar with Objective-C so I can't make the changes myself.

**Comment by karlvoskuil** [comment]
Ah, interesting!  I haven't used the square's colors in that way before, or else I would definitely have been annoyed by the same thing.  Thank you for writing.

I like your second solution better than the first.  As I noted in `squareNodeForSquare:`:

> The returned node should be treated as read-only.  Modification of the square node is neither expected nor recommended.

The color of each square is supposed to be completely controlled by the grid node; how the color is set is a private implementation detail.  So instead we should add methods (like you suggest) to the grid node to change the configured `squareColor` and `highlightColor` for the square.

The current grid node interface only allows setting those two colors for all squares. We could instead maybe allow each square to have its `normalColor` and `highlightColor` set individually.  So together the interface would be:

```
setSquareColor:(UIColor)squareColor;                             // sets normal color for all squares
setSquareColor:(UIColor)squareColor forSquare:(int)squareIndex;  // sets normal color for one square
setHighlightColor:(UIColor)highlightColor;                       // sets highlight color for all squares
setHighlightColor:(UIColor)highlightColor forSquare:(int)squareIndex;  // sets highlight color for one square
```

This is pretty good, but it means tracking individual colors for each square, which is slightly more complicated . . . and it's nice to avoid complication if most users don't need the feature.  A bit bloaty, I'd say.

So before we go any further, tell me what you think of the following two alternatives:
1. If you only use two colors for your squares, then you could configure the grid node with `squareColor` as one of them and `highlightColor` as the other.  Then changing the color of a square would be:
   
   ```
   grid!.setHighlight(forSquare: 0)
   ```
2. If your squares have more than two colors, then can you make the color be part of the content node, and not part of the square node?  The content is supposed to be completely under your control, but the square is supposed to be owned by the grid node.  I do something like this for the toolbar in the [Example project](https://github.com/hilogames/HLSpriteKit/blob/master/Example/Shared/HLCatalogScene.m#L186), but the same would work for grid node (sorry about Objective-C):

```
HLGridNode *gridNode = [[HLGridNode alloc] init];
NSMutableArray *gridContentNodes = [NSMutableArray array];

SKSpriteNode *redNode = [SKSpriteNode spriteNodeWithColor:[SKColor redColor] size:CGSizeMake(20.0f, 20.0f)];
[gridContentNodes addObject:redNode];

SKSpriteNode *orangeNode = [SKSpriteNode spriteNodeWithColor:[SKColor orangeColor] size:CGSizeMake(20.0f, 20.0f)];
[gridContentNodes addObject:orangeNode];

SKSpriteNode *yellowNode = [SKSpriteNode spriteNodeWithColor:[SKColor yellowColor] size:CGSizeMake(20.0f, 20.0f)];
[gridContentNodes addObject:yellowNode];

[gridNode setContent:gridContentNodes];
```

I think the reason the second solution appeals to me is that then you have complete control over your content—not just the backdrop color, but other properties as well.  To generalize it, you could make a content node of your own (excuse lousy Swift):

```
class SUContentNode : SKNode {
  func setBackgroundColor(backgroundColor: UIColor *)
  func animateBackgroundColor(from: UIColor, to: UIColor *)
  func setForegroundIcon(foregroundIcon: SKNode *)
  ...
}
```

**Comment by Sweeper777** [comment]
Thank you so much for the suggestions! I didn't know how to set the content of the squares!

**Comment by karlvoskuil** [comment]
Oh good!  Let me know if you have any other ideas or issues.
