### ISSUE TITLE
Can you reduce the number of nodes in HLGridNode?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#16]
I created a 10x20 grid node as I have said in my other issues.

```
    let grid = HLGridNode(gridWidth: 10, squareCount: 200, anchorPoint: CGPoint(x: 0.5, y: 0.5), layoutMode: .fill, squareSize: CGSize(width: 40, height: 40), backgroundBorderSize: 1, squareSeparatorSize: 2)
    self.addChild(grid!)
```

When I look at the node count at the bottom right, it says 404!

In the grid node, there should be 200 squares right? How can the total node count be double the number of squares? I understand that you need some node to put the content in, but can you remove that node if the content is `NSNull`?

**Comment by karlvoskuil** [comment]
Yes, each grid square has two nodes, no matter whether there is content or not. They support parts of the `HLGridNode` interface like `squareColor`.

Here is a question for you:
What parts of the `HLGridNode` interface are you using other than setting content?  The grid node does three things:
1. Lays out nodes in a grid, using properties `gridWidth`, `squareCount`, `anchorPoint`, `squareSize`, `backgroundBorderSize`, and `squareSeparatorSize`;
2. Manages the appearance of the nodes, using the highlight and enabled states and colors;
3. Reports on taps/clicks in the grid, through `squareAtPoint:` and also through delegate callbacks when set as a gesture target or `UIResponder`.

If you are using only the layout stuff, and not the appearance or interaction stuff, then maybe I should make a `HLGridLayoutManager` for you, which can update the layout without bothering with any of the other stuff.

The layout manager can help with interaction stuff, too: It can't do the gesture target stuff, or `UIResponder` stuff, but it could provide the equivalent of `squareAtPoint:` for you.

Does that sound interesting?

**Comment by Sweeper777** [comment]
Actually, I'm only using the grid node to set content and display things to the user (I.e. The first point). Do you mean that using grid node for only one purpose is wasteful? If that's the case, what should I use instead? I want to be able to set the contents of the grid using a 1D or 2D array.

**Comment by karlvoskuil** [comment]
Sounds like `HLGridNode` might do more than you need it to.  But that might be fine.  I have two comments:
1. Feel free to use `HLGridNode` just as you are using it.  If it works for now, then don't worry about how many extra nodes it is creating.
2. But if performance or node count becomes a problem, then try something else.  It sounds like you all you need is something which calculates and sets the position of a bunch of nodes.  If so, then you could just do it yourself in a loop.  But it's nice to have a reusable object do it for you.  I have "layout managers" to do this kind of work for me.  I will make you an `HLGridLayoutManager` and you can try it, and see if you like it.  It won't create any extra nodes; it will just set the position of a bunch of nodes from a 1D array.  (I could also add an optional method for a 2D array . . . are you saying you want to be able to do _both_ 1D _and_ 2D?)

**Comment by Sweeper777** [comment]
Actually, performance issues seem to only appear on the simulator. I'm getting around 15 - 20 fps. But not on my real devices though (tested on my phone and iPad). So I don't think it is a problem.

Since my model is a 2D array, so I would prefer a method that accepts a 2D array.

This is my simplified model:

```
[
    [1,4,7],
    [2,5,8],
    [3,6,9]
]
```

And I want it to appear on screen like this:

```
1 2 3
4 5 6
7 8 9
```

I'm currently converting my array to 1D like this:

```
    func flatten(_ array: [[MyModel?]]) -> [MyModel?] {
        var flat = [MyModel?]()
        for i in 0..<20 {
            for sub in array {
                flat.append(sub[i])
            }
        }
        return flat
    }

    grid.setContent(flatten(myArray).map { $0?.node ?? NSNull() })
```

My current implementation is fine IMO, so I don't think I will need an `HLGridLayoutManager`

**Comment by karlvoskuil** [comment]
Very good example!  It made me realize something about how we might want "columns before rows" behavior or else "rows before columns" behavior.

I'm going to work on an `HLGridLayoutManager` that takes a 2D array, just for fun.  I'll re-open to remind myself to follow up.

**Comment by karlvoskuil** [comment]
Okay, pushed 961b7431978d0a77eb666dfe6dae95d07c58533a to have an `HLGridLayoutManager` do layout with support for 2D arrays.

If you're interested, I'd love to have you try it and see if it works for you!

Here's how to do it with 2D arrays:
1. Initialize the layout manager using `initWithSquareSize:`.  (When using 2D arrays, there is no need to specify a constraint on `columnCount` or `rowCount`.)
2. Choose and set the layout manager's `fillMode`.  See the docs for `HLGridLayoutManagerFillMode`.  From your example, I think you want `HLGridLayoutManagerFillDownThenRight`.
3. Use the manager to layout your nodes.  Call `layoutWith2DArray:`.
4. You can attach the manager to a node using `hlSetLayoutManager`, but that's only if you need a place to retain it, and don't want to retain it somewhere else.

**Comment by Sweeper777** [comment]
How do I install the pod with the newest commit? I tried `pod update` and it doesn't seem to have a new version. What should I write in the Podfile in order to install the new update?

**Comment by karlvoskuil** [comment]
Use the head of the "master" branch on github.  I think this is the right syntax:

  pod 'HLSpriteKit', :git => 'https://github.com/hilogames/HLSpriteKit.git'

**Comment by Sweeper777** [comment]
I tried to use the new `HLGridLayoutManager` but I don't think I quite understand how to use it. I used the following code:

```
    let repeating: [SKSpriteNode?] = [SKSpriteNode?](repeating: nil, count: 20)
    var colors = [[SKSpriteNode?]](repeating: repeating, count: 10)
    for i in 0..<20 {
        colors[0][i] = SKSpriteNode(color: UIColor.white, size: CGSize(width: 20, height: 20))
    }
    let gridLayout = HLGridLayoutManager(squareSize: CGSize(width: 20, height: 20))!
    gridLayout.fillMode = .downThenRight
    self.hlSetLayoutManager(gridLayout)
    gridLayout.layoutWith2DArray(colors)
    self.hlLayoutChildren()
```

This should create a vertical line of white sprites, but it doesn't. When I run the app, nothing appears, and the node count is 1. Why?

**Comment by karlvoskuil** [comment]
Two things:
1. You need to add the sprite nodes to a parent node, probably `self.addChild()`.
2. Don't bother calling `hlSetLayoutManager()`, and don't call `hlLayoutChildren()`.  The latter just calls `gridLayout.layout(gridLayout.children)`, which is not what you want if you have a 2D array.

**Comment by Sweeper777** [comment]
Now I have this code:

```
    let repeating: [SKSpriteNode?] = [SKSpriteNode?](repeating: nil, count: 20)
    var colors = [[SKSpriteNode?]](repeating: repeating, count: 10)
    for i in 0..<20 {
        colors[5][i] = SKSpriteNode(color: UIColor.white, size: CGSize(width: 50, height: 50))
        self.addChild(colors[5][i]!)
    }
    let gridLayout = HLGridLayoutManager(squareSize: CGSize(width: 50, height: 50))!
    gridLayout.fillMode = .downThenRight
    gridLayout.layoutWith2DArray(colors)
```

And a single white block appears at the center of the screen, instead of a column of white blocks. I am really confused.

Can you show me a working example of HLGridLayout?

**Comment by karlvoskuil** [comment]
I think the problem is that you're passing an array of type `[[SKSpriteNode?]]` to a method which expects an array of type `[[SKSpriteNode]]!`.

This brings us back to the fact that you have to use `NSNull()` to represent nil when building an array which is bridgeable to Objective-C.

This works, but I'm not sure if it's the preferred way to do it:

```
    var colors = [[AnyObject]]()
    for i in 0..<20 {
      colors.append([AnyObject]())
      for j in 0..<10 {
        if ((i + j) % 2 == 0) {
          let node = SKSpriteNode(color: UIColor.white, size: CGSize(width: 50, height: 50))
          colors[i].append(node)
          self.addChild(node)
        } else {
          colors[i].append(NSNull())
        }
      }
    }
```

If I change my Objective-C declaration to specify the types:

```
- (void)layoutWith2DArray:(NSArray <NSArray <id> *> *)nodeArrays;
```

...then we can even get a compiler error if we try to add `nil` to the array.  But again, I'm not sure that's what I should be doing.  I think this is a common gotcha with using Obj-C in Swift.

**Comment by karlvoskuil** [comment]
Or I guess this is more similar to your original code:

```
    let repeating: [AnyObject] = [AnyObject](repeating: NSNull(), count: 20)
    var colors = [[AnyObject]](repeating: repeating, count: 10)
    for i in 0..<20 {
      colors[5][i] = SKSpriteNode(color: UIColor.white, size: CGSize(width: 50, height: 50))
      self.addChild(colors[5][i] as! SKNode)
    }
```

**Comment by Sweeper777** [comment]
Thanks! I tried that and it works!

**Comment by karlvoskuil** [comment]
Cool!  Let me know if you get any ideas on how to make the bridging work better from Swift to Obj-C.  I guess I really just need to start porting some day.

**Comment by Sweeper777** [comment]
Can you issue an update for this, so that I can update the pod using `pod update` instead of changing the pod file?

**Comment by karlvoskuil** [comment]
Sure.  Version 1.3.0 released!
