### ISSUE TITLE
Maybe add a HLLinearLayout?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#18]
This is only a suggestion.

HLLinearLayout basically lays out nodes in a linear fashion. There can be a property that sets whether the layout should lay nodes out from left to right, right to left, top to bottom, or bottom to top. The client code can also set how big the spacing between nodes will be.

It's basically a SpriteKit version of `UITableView`, except it's not a visible thing, just a layout manager. This can be useful in scenes like game settings and main menus.

What do you think?

**Comment by karlvoskuil** [comment]
I think this will work well with `HLGridLayoutManager`!  My current idea is to allow the grid manager to be created with two important options:
1. a limit of either rows or columns
2. an option for whether to fill nodes into the grid top-to-bottom or left-to-right (and every permutation of those two things)

That should cover it, I think!  I could make a HLLinearLayoutManager just as a more-discoverable way of doing the same thing.

One other idea is to do let the grid do the constant-spacing thing, but create a linear layout manager to be more like a `UIStackView`.

**Comment by karlvoskuil** [comment]
I'm thinking that HLGridLayoutManager covers this use-case, so I guess I'll close this for now.
