### ISSUE TITLE
can you submit recently version to cocoapod?

### ISSUE THREAD

**Issue by phpmaple** [hilogames/HLSpriteKit#2]
thx!

**Comment by karlvoskuil** [comment]
Okay! Yeah, it's been a while. Released 0.9.7 from master.  There are some API changes in this release, but hopefully nothing too painful.  Cocoadocs for the new version should be on the way.

I haven’t gotten much feedback yet, so let me know what’s working and what’s not.  The whole HLGestureTarget still seems a bit user-unfriendly.
