### ISSUE TITLE
When I use Swift, and import HLSpriteKit with cocoapod

### ISSUE THREAD

**Issue by phpmaple** [hilogames/HLSpriteKit#20]
it show error:
SKNode have no size

**Comment by karlvoskuil** [comment]
Does this happen in a newly created project (using the "Game" template)?

**Comment by phpmaple** [comment]
@karlvoskuil I Run it on Swift4 and Xcode 9

**Comment by karlvoskuil** [comment]
I cannot reproduce.  Here's what I did:

1. In Xcode 9 (9A235), create new Swift project from "Game" template.
1. Create Podfile in root directory:

        platform :ios, '11.0'
        source 'https://github.com/CocoaPods/Specs.git'
        use_frameworks!
        target 'SwiftHLSpriteKitTest' do
          pod 'HLSpriteKit', '~> 1.0'
        end

1. `pod install`
1. Put the following code in `GameScene.swift`:

        import HLSpriteKit

        // Create HLLabelButtonNode
        let button = HLLabelButtonNode.init(color: SKColor(white: 0.0, alpha: 1.0), size: CGSize(width: 50.0, height: 20.0))
        self.addChild(button!)

    (Sorry if that Swift is weird; I haven't learned the language yet!)

1. Compile and run.

I see no errors.

**Comment by phpmaple** [comment]
In the file "HLItemContentNode", and method "size", it show error
Multiple methods named `size` found with mismatched result, parameter type or attributes

**Comment by phpmaple** [comment]
I also see some commented:
```
// Commented out: This generates code without warnings if child is declared SKNode *.
//    SEL selector = @selector(setSize:);
//    NSMethodSignature *methodSignature = [child methodSignatureForSelector:@selector(setSize:)];
//    if (methodSignature) {
//      NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:methodSignature];
//      [invocation setTarget:child];
//      [invocation setSelector:selector];
//      [invocation setArgument:&selfSize atIndex:2];
//      [invocation invoke];
//    }
```

I guess Xcode9 treat size and setsize is error

**Comment by phpmaple** [comment]
I Found xcode8 is ok, but xcode9 run fail, and I use objective-c and swift together

**Comment by karlvoskuil** [comment]
Okay, got it!  Thanks for the bug report.  I'm working on a solution.

**Comment by karlvoskuil** [comment]
@phpmaple Are you building for macOS?  I was able to reproduce under macOS and I've got a fix which seems to work for me.  If you are building for macOS, I'll push the fix and see if it works for you.  Thanks again.

**Comment by karlvoskuil** [comment]
I pushed 8135c28fecd46061ab880bd4e7b5916beab0ff74 to the master branch, which I believe fixes the problem under macOS.

Does this fix the problem for you?  You can change your Podfile to use the master version of HLSpriteKit like this:

    pod 'HLSpriteKit', :git => 'https://github.com/hilogames/HLSpriteKit'

**Comment by karlvoskuil** [comment]
Oh hang on, I can also reproduce on actual iPhone 7 device (not just simulator).  Probably I'll have to push a similar fix for iOS as macOS.

**Comment by karlvoskuil** [comment]
Pushed ca4700169ae7d72f317a542e9267f8860eaa1585; let me know if this helps you!

**Comment by phpmaple** [comment]
great!! it works
Thanks, you can merge to master

**Comment by karlvoskuil** [comment]
Hooray!  Thanks again.
