### ISSUE TITLE
compiler error when building for the device: multiple methods named 'size' found with mismatched result, parameter type or attributes

### ISSUE THREAD

**Issue by qiweiye** [hilogames/HLSpriteKit#21]
The building for simulator is OK, and works great!

But try to build on iOS device, get several errors(all errors are similar):

HLSpriteKit/HLSpriteKit/HLLayoutManager.m:36:12: error: multiple methods named 'size' found with mismatched result, parameter type or attributes
    return [node size].width;

 In module 'SpriteKit' imported from Pods/HLSpriteKit/HLSpriteKit/HLLayoutManager.m:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/System/Library/Frameworks/SpriteKit.framework/Headers/SKScene.h:58:30: note: also found
@property (nonatomic) CGSize size;
                             ^~~~
In module 'SpriteKit' imported from Pods/HLSpriteKit/HLSpriteKit/HLLayoutManager.m:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/System/Library/Frameworks/SpriteKit.framework/Headers/SKSpriteNode.h:163:30: note: also found
@property (nonatomic) CGSize size;
                             ^~~~
In module 'SpriteKit' imported from Pods/HLSpriteKit/HLSpriteKit/HLLayoutManager.m:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/System/Library/Frameworks/SpriteKit.framework/Headers/SKVideoNode.h:66:30: note: also found
@property (nonatomic) CGSize size;

**Comment by karlvoskuil** [comment]
Thank you for the report!  I think this has been fixed in [version 1.6.0](https://github.com/hilogames/HLSpriteKit/tree/1.6.0) and after, but I may have missed one or two of them.  Am I right that you are using an older version, and if so, are you able to try again with a more recent version?

**Comment by qiweiye** [comment]
Thanks! Yes, after upgrading the latest version, the problem is fixed.

**Comment by karlvoskuil** [comment]
Great!  Please let me know if you have any comments or problems as you use HLSpriteKit.
