### ISSUE TITLE
Fatal Crash ~ [UIGestureRecognizer _delegateShouldRecieveTouch] - HLMenuNode - Scene Transition

### ISSUE THREAD

**Issue by andrewjaykeller** [hilogames/HLSpriteKit#5]
I am experiencing a fatal crash with HLMenuNode.

I can force the crash when i double tap during the transition. I am using slide open door transition effect with a duration of 0.5 seconds. I "pause" the incoming and outgoing scenes, although i have tried the different ways. 

It shall also be noted that i am using these buttons to launch scenes.

**Comment by andrewjaykeller** [comment]
Hmm so willMoveFromView in HLScene appear to remove the gestureRecognizer... Maybe the right question to ask is when does willMoveToView get called in an open doors close doors transition?

**Comment by karlvoskuil** [comment]
Thank you for the report!
Yeah, good question about the timing of the willMoveFromView.  There might be some bad assumptions in the HLSpriteKit code.

As a shot in the dark I tried doing some fast tapping on my app that uses an HLMenuNode to do scene transitions. But no crash.

Two thoughts:

1) The scene owns the menu node and the gesture delegate, and probably nothing else is retaining them. If the scene and menu node and gesture recognizer are all being deallocated during that transition, then it makes sense the timing would be important.  Do you retain the scene in the view controller of the SKView? If not, try putting an ivar or static variable in the view controller (or in whatever is doing the presenting of scenes) to retain the scene even when it's not being presented, and see if you still get the crash.  (If _not_, then I bet we can easily make a small test case to reproduce the crash.)

2) Is the crash EXC_BAD_ACCESS?  The UIGestureRecognizer delegate pointer is weak, and so shouldn't be dereferenced if the HLScene is not around. I guess the UIGestureRecognizer itself is being double-deallocated? Maybe try running Instruments "Zombies", and we'll get lucky with more detail on the location of the crash.

**Comment by karlvoskuil** [comment]
Have you been able to reproduce, @pushtheworldllc?

**Comment by andrewjaykeller** [comment]
No i ended up making it so this case could not happen in app :) I think it was really just moving too quickly between the gestures. There is also a big risk when the scene owns the menu nodes, i think that really could have been the root. Any way i will close this!

**Comment by karlvoskuil** [comment]
Okay, thanks!  I'll keep an eye out either way.
